server:
  port: 1111
spring:
  profiles:
    active: peer1


eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: Peer1-Eureka-Server
#    ip-address: 127.0.0.1

  client:
    #fetch-registry: false
    #register-with-eureka: false
    service-url:
      defaultZone: http://peer2:1112/eureka/
